---
- name: Install git on Ubuntu servers
  hosts: Ubuntu
  tasks:
    - name: Install git using apt
      apt:
        name: git
        state: present
        update_cache: yes
- name: Install git on RHEL servers
  hosts: RedHat
  tasks:
    - name: Install git usig yum
      yum:
        name: git
        state: present
        update_cache: yes
...
