---
- name: Delete if file is executable
  hosts: all
  tasks:
    - name: Check for detailed infor of the file
      stat:
        path: /tmp/file1
      register: a
    - name: Display output of the above module
      debug:
        var: a
    - name: Del file if it is exe
      file:
        name: /tmp/file1
        state: absent
      when: a.stat.executable == true
...
